#!/bin/bash

echo "🐝 Words of Champions - GitHub Push Script 🐝"
echo "=============================================="
echo ""
echo "Step 1: Create the GitHub Repository"
echo "-------------------------------------"
echo ""
echo "In the browser window that opened:"
echo ""
echo "  Repository name: molly-words-of-champions"
echo "  Description: Words of Champions spelling bee practice website"
echo "  Visibility: ✓ Public"
echo ""
echo "  Do NOT check:"
echo "    [ ] Add a README file"
echo "    [ ] Add .gitignore"
echo "    [ ] Choose a license"
echo ""
echo "Click 'Create repository'"
echo ""
read -p "Press ENTER after you've created the repository..."
echo ""
echo "Step 2: Pushing Code to GitHub"
echo "--------------------------------"
echo ""

# Push to GitHub
git push -u origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Success! Code pushed to GitHub!"
    echo ""
    echo "Step 3: Enable GitHub Pages"
    echo "----------------------------"
    echo ""
    echo "Opening GitHub Pages settings..."
    sleep 2
    open "https://github.com/emilystat/molly-words-of-champions/settings/pages"
    echo ""
    echo "In the browser:"
    echo "  1. Under 'Source', select: main"
    echo "  2. Click 'Save'"
    echo "  3. Wait 1-2 minutes"
    echo ""
    echo "=============================================="
    echo "Your site will be live at:"
    echo "https://emilystat.github.io/molly-words-of-champions/"
    echo "=============================================="
else
    echo ""
    echo "❌ Push failed. Common issues:"
    echo ""
    echo "1. Repository not created yet - go back and create it"
    echo "2. Authentication needed - you may need to enter your GitHub username/password"
    echo "   (Note: GitHub requires a Personal Access Token instead of password)"
    echo ""
    echo "To try again, run: bash push-to-github.sh"
fi
